### ISSUE TITLE
Changing city color

### ISSUE THREAD

**Issue by YBerkay** [erdigokce/turkey-map-react#1]
Hello Erdi,

How can I change city color by plateNumber. I don't want to change  color of the all cities.

**Comment by erdigokce** [comment]
Hello,

Sorry for late response. For example : 

``

**Comment by erdigokce** [comment]
> Hello Erdi,
> 
> How can I change city color by plateNumber. I don't want to change color of the all cities.

Hello,

Maybe **City Component Wrapping** feature works for you. You can wrap a div and style it based on city data.

Please see more on readme : 
https://github.com/erdigokce/turkey-map-react#city-component-wrapping

**Comment by ErtugrulBEKTIK** [comment]
Hi,

As Erdi said, you can use cityWrapper prop to achieve that. Here is an example:

```
cityWrapper={(cityComponent, cityData) => (
    <g fill={cityData.plateNumber % 2 == 0 ? 'red' : 'green'}>
        {cityComponent}
    </g>
)}
```

**Comment by ErtugrulBEKTIK** [comment]
Hi,

I can achieve that by using cityWrapper and customStyle props together. Here is an example:

```
cityWrapper={(cityComponent, cityData) => (
    <g fill={cityData.plateNumber % 2 == 0 ? 'red' : 'blue'}>
        {cityComponent}
    </g>
)}
customStyle={{
    idleColor: 'inherit',
    hoverColor: 'purple',
}}
```
